### ISSUE TITLE
Add autocompletion and type-hinting on TYPO3 context API

### ISSUE THREAD

**Issue by ipf** [cedricziel/idea-php-typo3-plugin#240]
The TYPO3 code can be found [here](https://github.com/TYPO3-CMS/core/blob/a029ab3e8229256cc7046d555749294628f82183/Classes/Context/Context.php#L68)

Expected:
Using a statement such as `$languageAspect = GeneralUtility::makeInstance(TYPO3\CMS\Core\Context\Context::class)->getAspect('language');` should result in the proper type-hinting for `$languageAspect` and also provide autocompletion for the selected aspect.

This only works in TYPO3 9, see https://docs.typo3.org/typo3cms/extensions/core/latest/Changelog/9.4/Feature-85389-ContextAPIForConsistentDataHandling.html

**Comment by cedricziel** [comment]
@bmack could we alter the `AspectInterface`, so the name can be inferred statically?

Like:

```
public function getName() : string {
	return 'user';
}
```

Parsing the stuff in the context class constructor is guaranteed to break and I would like to provide completion for the context names.

I also think it might be better if the names are not inlined in the context class.

**Comment by bmack** [comment]
uuuh, I see @ipf working with the context API. I thought I was the only one understanding and using this.... NICE.

Main issue with that is that an aspect does not know its name (see useraspect - it's used twice). Because it is kind-a inject into a context, you could even use the same aspect twice in one context.

**Comment by bmack** [comment]
Can we do some kind of "getReflectedAspectsWithName" internal API thingy within T3 to use that as base "I'll tell you what I have, what types and what names are there?"

**Comment by cedricziel** [comment]
That API is super nice! - Thank you for solving the problem so we don't have to over and over again :)

Sneak preview - that's what's currently up with #242 :

![image](https://user-images.githubusercontent.com/418970/45217827-db190c80-b2a5-11e8-8992-43ae168af840.png)

The aspects are referred to by alias - such as `frontend.user`. To have some meaningful support in the IDE, I need to create a mapping between these aliases and their FQCNs. I can do this in a static map for the default aspects since I don't expect them to change that often.

But when another aspect is added via middleware (such as a principal for example), how do I detect those then? I cannot execute some php-code. I always have to look at patterns, such as method calls.

Do you think it's feasible to rely on a pattern like "look at all `setAspect` calls in middlewares", or do you see another pattern, where we can make sure, we don't collect false-positives? Are there special places where aspects are added besides middlewares?

That's where a statically dumped container really shines, and dynamic dependencies fall really, really short. :/

**Comment by bmack** [comment]
Let's get olly in here, he and Susi basically set up the architecture, I'm not the master brain actually.

Btw / unrelated: The day when you get remove the `$GLOBALS['TSFE']` analyzer, I will send you a beer with DHL! That day will come.

**Comment by cedricziel** [comment]
When that day comes - You'll get one as well! :)

**Comment by cedricziel** [comment]
Feature itself is implemented - re-opening for discussing further means.
