### ISSUE TITLE
PhpStorm / IntelliJ 2019.3 support

### ISSUE THREAD

**Issue by saschaende** [cedricziel/idea-php-typo3-plugin#295]
Wasnt there a support for displaying the translations for "LLL:EXT:bdi_core/Resources/Private/Language/locallang_db.xlf:tx_bdicore_domain_model_week" in TCA? Was it removed? Or was this another plugin?

I reinstalled phpstorm and now i am missing this feature.

**Comment by saschaende** [comment]
I tested it and reinstalled php storm 2018.3, there TCA files work. Autocomplete and display of translations.

In the latest 2019.3 this does all not work. Also there are missing in NEW: Extbase Controller, Viewhelper. Perhaps there are other things also missing, i dont know.

Is a compatibility release for phpstorm 2019 planned?

**Comment by cedricziel** [comment]
Hi @saschaende , currently, 2019.3 is _not_ supported, and the plugin falls back to a much older version with a limited featureset.

Due to a bc-break on a specific component, I am struggeling to keep the features alive that are already in it. I'm working on it, but cant promise a fast solution for the problem as this is (of course) a side-project.

**Comment by cedricziel** [comment]
@saschaende fixed and new release submitted as v0.4.1 is pending approval of JetBrains

**Comment by saschaende** [comment]
They are very slow with approval :D
