### ISSUE TITLE
Compatibility to PhpStorm 2021.2

### ISSUE THREAD

**Issue by dahaupt** [cedricziel/idea-php-typo3-plugin#357]
The plugin is not compatible with PhpStorm 2021.2:

```
Incompatible: requires IDE build 211.* or older
```

**Versions**
PhpStorm 2021.2

**Comment by grempa** [comment]
+1

**Comment by liayn** [comment]
see https://github.com/cedricziel/idea-php-typo3-plugin/pull/356

**Comment by bernhardberger** [comment]
Is there any fix in sight?

**Comment by sbuerk** [comment]
+1
+1
+1

**Comment by J4fix** [comment]
+1²

**Comment by fritzdacat** [comment]
+1

**Comment by ftrojahn** [comment]
+1

**Comment by saschaende** [comment]
+1

**Comment by EricBode** [comment]
+1

**Comment by infabo** [comment]
+1

**Comment by saschaende** [comment]
Hier mal eine Liste was ich benutze:

https://plugins.jetbrains.com/plugin/11151-typo3-fluid--enterprise
https://plugins.jetbrains.com/plugin/11243-typo3-typoscript--enterprise
https://plugins.jetbrains.com/plugin/8098-typo3-xliff-utility
https://plugins.jetbrains.com/plugin/14827-typo3--coding-tools
https://plugins.jetbrains.com/plugin/7219-symfony-support/

Diese Plugins sind alle up2date und reichen eigentlich völlig aus, wie ich mittlerweile feststelle.

Cedric Ziel habe ich übrigens bereits am 17.09. per E-Mail angeschrieben, aber keine Antwort erhalten:

"Hi, benötigst Du eine Spende, um das Plugin kompatibel zum neuesten PHPStorm zu machen?"

**Comment by liayn** [comment]
@saschaende Thanks. I pinged him on Slack already on Sept 1st. No response either. Maybe he is on a long vacation. ;-)

**Comment by saschaende** [comment]
@liayn Hopefully he is healthy and it is not an endless vacation to the stars.

**Comment by liayn** [comment]
> 
> Meine Plugins

A little of topic here, but I use https://github.com/garfieldius/t3ll/ instead of XLIFF Utility ;-)

**Comment by cedricziel** [comment]
Hi folks;

this project is in a lingering state. Professionally, I dont have any association to TYPO3 anymore. I am trying to keep this up to date, but platform version 201 is not easy to satisfy and I have been transparent about both. 

I am not considering accepting "new" financial support fair. Keeping this project up to date is not sustainable for me. I would love to do otherwise (there is tons of good stuff possible, for example the unpublished fluid language support plugin that also lives in this repo), but in addition to my full-time job, I cannot justify spending a lot of time on it as I'm already over capacity.

I will continue maintaining this in a best-effort way.

Thanks for reading!

Closing via v0.7.2
