### ISSUE TITLE
Support custom project structure

### ISSUE THREAD

**Issue by Smove** [cedricziel/idea-php-typo3-plugin#87]
There should be a settings where we can define custom extension directory. Currently only best-practices structures are supported.

Example:
Add `<projectpath>/ext` to extension root directories, so the plugin can look in these directory when resolving some `EXT:*` path

**Comment by cedricziel** [comment]
That's of course desirable - I have thought a lot about the discovery-process and I would like to get it down to a very simple ruleset that embraces best-practices. The main point is inferring the extension key.

Extensions living in `typo3conf/ext` or `sysext/`:

* extension key kann be inferred from the directory name
* currently supported for classic folder layout and composer based instances since the the composer scripts pull the packages in the right place

Extensions living outside those two directories:

* extension key can be inferred by one of the following ways:
  * reading the parent directory name of an `ext_emconf` file
  * reading a `composer.json` `extra` key (`extra.typo3/cms.extension-key`) (Implementation in the TYPO3 Composer Plugin: https://github.com/TYPO3/CmsComposerInstallers/blob/cdb820b17e9cc7d78a1168b00b2e9e0af0047f3f/src/Plugin/Util/ExtensionKeyResolver.php#L32 )
  * reading the `installerName` composer.json key (in the TYPO3 composer scripts as well)

Priority and ordering would be:

1. composer.json `extra.typo3/cms.extension-key`
2. composer.json `installerName`
3. folder name of parent directory containing ext_emconf if parent is t3conf/ext or sysext

I would really like to avoid other methods such as custom mappings, do you think we can get along with this, @Smove , @RauchF ?

**Comment by Smove** [comment]
That might be a good solution 👍

**Comment by cedricziel** [comment]
I created a PR to fix the issue with #88 and attached a build-artifact. Could you try it by copying it to your local plugin path?

**Comment by Smove** [comment]
The artifact worked for me if i use a correct directory name. If the directory name of the extension is not the extension-key from composer.json, the file cannot be resolved. I don't know if anyone whould ever do this .

**Comment by cedricziel** [comment]
Can you invalidate the caches and restart the IDE to see if the problem persists? IMHO the only way this could happen is if your extensions' composer.json doesnt have the correct package type set.

**Comment by Smove** [comment]
After invalidate cache(and restart) the custom extension key is rrecognized
